title: Yulek
email: yulek.conseil.creation@gmail.com
description: Write description
collections:
  articles:
    output: true
  illustrations:
    output: false
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
