backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"


collections:
  - name:      "articles"
    label:     "Articles"
    folder:    "_articles"
    create:    true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Titre de l'article", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "date"}
      - {label: "Image de couverture", name: "cover-image", widget: "image"}
      - {label: "Contenu de l'article", name: "content", widget: "markdown", required: false}
  - name:      "illustrations"
    label:     "Illustrations"
    folder:    "_illustrations"
    create:    true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - label:     "Pages"
    name:      "pages"
    files:
      - label:    "À propos"
        name:     "about"
        file:     "about/index.md"
        fields:
          - {label: Layout, name: layout, widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: "hidden", default: "home"}
          - {label: Description, name: description, widget: markdown}
          - {label: Contact, name: contact, widget: string, default: "yulek.conseil.creation@gmail.com"}
