backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"


collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.md"
        fields:
          - {label: Layout, name: layout, widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: "hidden", default: "home"}
          - {label: Description, name: description, widget: markdown}
          - {label: Contact, name: contact, widget: string, default: "yulek.conseil.creation@gmail.com"}
