backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"


collections:
  - name:      "Articles"
    label:     "Articles"
    folder:    "_articles"
    create:    true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Titre de l'article", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "date"}
      - {label: "Image de couverture", name: "cover-image", widget: "image"}
      - {label: "Contenu de l'article", name: "article-content", widget: "markdown", required: false}
  - name:      "Illustrations"
    label:     "Illustrations"
    folder:    "_illustrations"
    create:    true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
  - label:     "Pages"
    name:      "Pages"
    files:
      - label:    "À propos"
        name:     "About"
        file:     "/about/index.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string", default: "a-propos"}
          - {label: "Photo de profile", name: "profile-pic", widget: "image"}
          - {label: "Description", name: "description", widget: "markdown"}
